apiVersion: upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: crossplane
spec:
  id: crossplane
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: small
    minNodeCount: 3
