apiVersion: upbound.io/v1alpha1
kind: ClusterClaim
metadata:
  name: crossplane
spec:
  id: crossplane
  compositionSelector:
    matchLabels:
      provider: google
      cluster: gke
  parameters:
    nodeSize: small
